const figurasHistoricasPorPais = {
  Alemanha: ["Albert Einstein"],
  Polônia: ["Marie Curie"],
  "África do Sul": ["Nelson Mandela"],
  Itália: ["Leonardo da Vinci", "Vincenzo Bellini"],
  Índia: ["Mahatma Gandhi"],
  Inglaterra: ["Isaac Newton", "Winston Churchill", "Stephen Hawking"],
  México: ["Frida Kahlo"],
  "Estados Unidos": [
    "Rosa Parks",
    "George Washington",
    "César Chávez",
    "Martin Luther King Jr.",
  ],
  Egito: ["Cleópatra VII"],
  Paquistão: ["Malala Yousafzai"],
  França: ["Simone de Beauvoir", "Coco Chanel"],
  "Países Baixos": ["Vincent van Gogh"],
  Escócia: ["Alexander Graham Bell"],
};
